# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(606, 284)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.inputPageStart = QtWidgets.QSpinBox(self.centralwidget)
        self.inputPageStart.setMinimum(1)
        self.inputPageStart.setMaximum(1000)
        self.inputPageStart.setObjectName("inputPageStart")
        self.gridLayout.addWidget(self.inputPageStart, 1, 0, 1, 1)
        self.inputPageURL = QtWidgets.QTextEdit(self.centralwidget)
        self.inputPageURL.setMaximumSize(QtCore.QSize(16777215, 60))
        self.inputPageURL.setObjectName("inputPageURL")
        self.gridLayout.addWidget(self.inputPageURL, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.inputPageEnd = QtWidgets.QSpinBox(self.centralwidget)
        self.inputPageEnd.setMinimum(1)
        self.inputPageEnd.setMaximum(1000)
        self.inputPageEnd.setObjectName("inputPageEnd")
        self.gridLayout.addWidget(self.inputPageEnd, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonCancel = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCancel.setObjectName("buttonCancel")
        self.horizontalLayout.addWidget(self.buttonCancel)
        self.buttonSave = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSave.setObjectName("buttonSave")
        self.horizontalLayout.addWidget(self.buttonSave)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pobierator Książek 9000"))
        self.label.setText(_translate("MainWindow", "Adres URL do strony internetowej"))
        self.label_3.setText(_translate("MainWindow", "Nr ostatniej strony do pobrania"))
        self.label_2.setText(_translate("MainWindow", "Nr pierwszej strony do pobrania"))
        self.buttonCancel.setText(_translate("MainWindow", "Anuluj"))
        self.buttonSave.setText(_translate("MainWindow", "Zapisz"))
